<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=default"></script>
# Lecture 6 -  MIT 18.065

Symmetric matrix's eigenvalues and eigenvectors.

In [1]:
import numpy as np

#### For each eigenvector $x$ and corresponding eigenvalue $\lambda$, $Ax=\lambda x$

In [63]:
A = np.asarray([[1,2,3], [2,1,5], [3,5,1]])
np.linalg.matrix_rank(A)
w, v = np.linalg.eig(A)
for i in range(A.shape[0]):
    print(np.allclose(np.dot(A, v[:,i]), w[i]*v[:,i]))

True
True
True


For square matrix, $S=Q\Lambda Q^{T}$, no need to be symmetric

In [86]:
A = np.asarray([[1,2,3], [2,1,5], [3,5,111]])
w, v = np.linalg.eig(A)
np.allclose(A, np.dot(np.dot(v, np.diag(w)), v.T))

True

#### All eigenvectors are orthogonal.

In [65]:
A = np.asarray([[1,2,3], [2,1,5], [3,5,1]])
np.linalg.matrix_rank(A)
w, v = np.linalg.eig(A)
np.allclose(np.dot(v[:,0],v[:,1]), 0),\
np.allclose(np.dot(v[:,0],v[:,2]), 0),\
np.allclose(np.dot(v[:,1],v[:,2]), 0)

(True, True, True)

#### For the unsymmetric matrix. Eigenvectors are not orthogonal.

In [71]:
B = np.asarray([[7,1,2], [11,3,9], [3,5,1]])
w, v = np.linalg.eig(B)
np.allclose(np.dot(v[:,0],v[:,1]), 0),\
np.allclose(np.dot(v[:,0],v[:,2]), 0),\
np.allclose(np.dot(v[:,1],v[:,2]), 0)

(False, False, False)

#### For the unsymmetric matrix. Singular vectors are orthogonal.

In [70]:
B = np.asarray([[7,1,2], [11,3,9], [3,5,1]])
U, S, V = np.linalg.svd(B)
np.allclose(np.dot(U[:,0],U[:,1]), 0),\
np.allclose(np.dot(U[:,0],U[:,2]), 0),\
np.allclose(np.dot(U[:,1],U[:,2]), 0),\
np.allclose(np.dot(V[:,0],V[:,1]), 0),\
np.allclose(np.dot(V[:,0],V[:,2]), 0),\
np.allclose(np.dot(V[:,1],V[:,2]), 0)

(True, True, True, True, True, True)

#### Compare the eigenvalue and singular value
For symmetric matrix, eigenvalue equals to singular value.

In [69]:
A = np.asarray([[1,2,3], [2,1,5], [3,5,1]])
np.linalg.matrix_rank(A)
w, v = np.linalg.eig(A)
U, S, V = np.linalg.svd(A)

np.allclose(v[:,0], -V[0]),\
np.allclose(v[:,1], V[2]),\
np.allclose(v[:,2], -V[1])

(True, True, True)

In [81]:



# B = np.asarray([[7,1,2], [11,3,9], [3,5,1], [17,13,4]])
# U, S, V = np.linalg.svd(B)
# np.linalg.svd(B)







array([[1., 2., 3.],
       [2., 1., 5.],
       [3., 5., 1.]])

## 1. pure dot product

In [3]:
np.dot(A, B)

array([[ 52, 100],
       [ 69,  69],
       [ 34,  40],
       [ 62,  46]])

## 2. outer product

In [4]:
res = np.zeros((4, 2), dtype=int)
for i in range(3):
    res += np.outer(A.T[i], B[i])
res

array([[ 52, 100],
       [ 69,  69],
       [ 34,  40],
       [ 62,  46]])

## Problems for Lecture 1

$1$. Give an example where a combination of three nonzero vectors in $R^4$ is the zero vector. Then write your example in the form $Ax = \mathbf{0}$. What are the shapes of $A$ and $x$ and $\mathbf{0}$ ? 

In [20]:
u = np.array([1,2,3,4])
v = np.array([5,6,7,8])
A = np.array([u, v, u+v]).T
x = np.array([1,1,-1]).reshape((3,1))
res = np.dot(A, x)
print("A = {0}".format(A))
print("x = {0}".format(x))
print("res = {0}".format(res))

A = [[ 1  5  6]
 [ 2  6  8]
 [ 3  7 10]
 [ 4  8 12]]
x = [[ 1]
 [ 1]
 [-1]]
res = [[0]
 [0]
 [0]
 [0]]


$4$. $x$ is $(1,-1,0)$, $y$ is $(1,0,-1)$. Because the rank of ones(3,3) is 1, you can only find two independent vector with $Ax=0$. $

$9$. $m=3$, $n\geq3$, $r=3$

$18$.
$$\begin{equation*}\left[\begin{matrix}0 & A \\0 & A \\\end{matrix}\right]=\left[\begin{matrix} C \\ C \\\end{matrix}\right]\left[\begin{matrix} 0 & R \\\end{matrix}\right]\end{equation*}$$