<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=default"></script>
# Lecture 6 -  MIT 18.065

Symmetric matrix's eigenvalues and eigenvectors.

In [22]:
import numpy as np

### 1. For each eigenvector $x$ and corresponding eigenvalue $\lambda$, $Ax=\lambda x$

In [63]:
A = np.asarray([[1,2,3], [2,1,5], [3,5,1]])
np.linalg.matrix_rank(A)
w, v = np.linalg.eig(A)
for i in range(A.shape[0]):
    print(np.allclose(np.dot(A, v[:,i]), w[i]*v[:,i]))

True
True
True


### 2. For square matrix, $S=Q\Lambda Q^{T}$, no need to be symmetric

In [86]:
A = np.asarray([[1,2,3], [2,1,5], [3,5,111]])
w, v = np.linalg.eig(A)
np.allclose(A, np.dot(np.dot(v, np.diag(w)), v.T))

True

### 3. For symmetric matrix, eigenvectors are orthogonal.

In [4]:
A = np.asarray([[1,2,3], [2,1,5], [3,5,1]])
np.linalg.matrix_rank(A)
w, v = np.linalg.eig(A)
np.allclose(np.dot(v[:,0],v[:,1]), 0),\
np.allclose(np.dot(v[:,0],v[:,2]), 0),\
np.allclose(np.dot(v[:,1],v[:,2]), 0)

(True, True, True)

### 4. For the unsymmetric matrix, eigenvectors are not orthogonal.

In [71]:
B = np.asarray([[7,1,2], [11,3,9], [3,5,1]])
w, v = np.linalg.eig(B)
np.allclose(np.dot(v[:,0],v[:,1]), 0),\
np.allclose(np.dot(v[:,0],v[:,2]), 0),\
np.allclose(np.dot(v[:,1],v[:,2]), 0)

(False, False, False)

### 5. For the unsymmetric matrix. Singular vectors are orthogonal.

In [70]:
B = np.asarray([[7,1,2], [11,3,9], [3,5,1]])
U, S, V = np.linalg.svd(B)
np.allclose(np.dot(U[:,0],U[:,1]), 0),\
np.allclose(np.dot(U[:,0],U[:,2]), 0),\
np.allclose(np.dot(U[:,1],U[:,2]), 0),\
np.allclose(np.dot(V[:,0],V[:,1]), 0),\
np.allclose(np.dot(V[:,0],V[:,2]), 0),\
np.allclose(np.dot(V[:,1],V[:,2]), 0)

(True, True, True, True, True, True)

### 5 .Compare the eigenvalue and singular value
For symmetric matrix, eigenvalue equals to singular value.

In [69]:
A = np.asarray([[1,2,3], [2,1,5], [3,5,1]])
np.linalg.matrix_rank(A)
w, v = np.linalg.eig(A)
U, S, V = np.linalg.svd(A)

np.allclose(v[:,0], -V[0]),\
np.allclose(v[:,1], V[2]),\
np.allclose(v[:,2], -V[1])

(True, True, True)

### 6. $A$ is unsymmetric, $AA^{T}$ eigenvalue is square of A singular value

In [15]:
B = np.asarray([[7,1,2], [11,3,9], [3,5,1], [17,13,4]])
U, S, V = np.linalg.svd(B)
A = np.dot(B, B.T)
w, v = np.linalg.eig(A)

np.allclose(S[0]**2, w[0]),\
np.allclose(S[1]**2, w[1]),\
np.allclose(S[2]**2, w[2])


(True, True, True)

### 7. $B$ is $4\times3$ matrix, $B^{T}B$ is $3\times3$, $BB^{T}$ is $4\times4$
$B^{T}B$ has 3 eigenvalue. $BB^{T}$ has 4 eigenvalue, three of them are same with $B^{T}B$, another one is 0
<br> Non-zero eigenvalues are the same.

In [141]:
B = np.asarray([[7,1,2], [11,3,9], [3,5,1], [17,13,4]])
A1 = np.dot(B.T, B)
A2 = np.dot(B, B.T)
w1, v1 = np.linalg.eig(A1)
w2, v2 = np.linalg.eig(A2)
np.allclose(w1[0], w2[0]),\
np.allclose(w1[1], w2[2]),\
np.allclose(w1[2], w2[1]),\
np.allclose(0, w2[3])

(True, True, True, True)

For $BB^{T}$, eigenvalue $0$ correspondes to eigenvector, which also in nullspace.

In [161]:
from scipy.linalg import null_space
np.allclose(-v2[:, -1], null_space(A2).T)
np.linalg.matrix_rank(null_space(A2)*np.linalg.svd(B)[0][-1])

np.dot(np.linalg.svd(B)[0][-1].reshape((1, 4)), null_space(A2))/\
np.linalg.norm(np.linalg.svd(B)[0][-1])/\
np.linalg.norm(null_space(A2))

array([[0.43189847]])

For unsymmetric matrix $A$, size $m\times n$.<br>
$SVD(A)=U\Sigma V^{T}$<br>
$U=eig(AA^{T})$<br>
$V=eig(A^{T}A)$


In [88]:
A = np.asarray([[7,1,2], [11,3,9], [3,5,1], [17,13,4]])
w1, u = np.linalg.eig(np.dot(A, A.T))
w2, v = np.linalg.eig(np.dot(A.T, A))
U, S, VT = np.linalg.svd(A)

U[:, 0] = -U[:,0]
v = v.T
v[0] = -v[0]
v[1], v[2] = v[2], v[1].copy()

np.allclose(U, u),\
np.allclose(VT, v)

(True, True)

$Av=\sigma u$

In [102]:
A = np.asarray([[7,1,2], [11,3,9], [3,5,1], [17,13,4]])
U, S, VT = np.linalg.svd(A)
np.allclose(np.dot(A, VT[0]), U[:, 0]*S[0]),\
np.allclose(np.dot(U[:, 0], A), VT[0]*S[0])

(True, True)

In [126]:
np.dot(U[:, 0], np.asarray([S[0], 0, 0, 0]))
# np.dot(), VT[0])
B = \
np.dot(np.dot(A, VT[0].reshape((3, 1))), VT[0].reshape(1, 3))+\
np.dot(np.dot(A, VT[1].reshape((3, 1))), VT[1].reshape(1, 3))+\
np.dot(np.dot(A, VT[2].reshape((3, 1))), VT[2].reshape(1, 3))
np.allclose(A, B)

True

In [133]:
(U[:, 0]*S[0]).reshape((4, 1))*VT[0], VT[0], U[:, 0]*S[0]

(array([[ 5.49321771,  3.36739589,  2.14242022],
        [10.70046538,  6.55948936,  4.17330872],
        [ 4.22481964,  2.58985554,  1.64772989],
        [17.36327258, 10.64385499,  6.77188275]]),
 array([-0.80901007, -0.49593104, -0.31552355]),
 array([ -6.79004862, -13.22661581,  -5.22220897, -21.46236892]))

## Problems for Lecture 1

$1$. Give an example where a combination of three nonzero vectors in $R^4$ is the zero vector. Then write your example in the form $Ax = \mathbf{0}$. What are the shapes of $A$ and $x$ and $\mathbf{0}$ ? 

In [20]:
u = np.array([1,2,3,4])
v = np.array([5,6,7,8])
A = np.array([u, v, u+v]).T
x = np.array([1,1,-1]).reshape((3,1))
res = np.dot(A, x)
print("A = {0}".format(A))
print("x = {0}".format(x))
print("res = {0}".format(res))

A = [[ 1  5  6]
 [ 2  6  8]
 [ 3  7 10]
 [ 4  8 12]]
x = [[ 1]
 [ 1]
 [-1]]
res = [[0]
 [0]
 [0]
 [0]]


$4$. $x$ is $(1,-1,0)$, $y$ is $(1,0,-1)$. Because the rank of ones(3,3) is 1, you can only find two independent vector with $Ax=0$. $

$9$. $m=3$, $n\geq3$, $r=3$

$18$.
$$\begin{equation*}\left[\begin{matrix}0 & A \\0 & A \\\end{matrix}\right]=\left[\begin{matrix} C \\ C \\\end{matrix}\right]\left[\begin{matrix} 0 & R \\\end{matrix}\right]\end{equation*}$$