In [1]:
import numpy as np

In [8]:
A = np.random.rand(3, 4)
A

array([[0.67471543, 0.13541993, 0.51118397, 0.23693847],
       [0.63974657, 0.64899797, 0.17383939, 0.28681777],
       [0.94293995, 0.62750597, 0.61805803, 0.03387825]])

In [10]:
U, S, V = np.linalg.svd(A)

In [18]:
np.dot(U, U.T), np.dot(U.T, U), np.linalg.inv(U)==U.T

(array([[ 1.00000000e+00, -1.82536858e-16,  3.10043038e-16],
        [-1.82536858e-16,  1.00000000e+00,  2.49521181e-16],
        [ 3.10043038e-16,  2.49521181e-16,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -1.95951535e-16,  5.56485757e-17],
        [-1.95951535e-16,  1.00000000e+00, -1.09395876e-16],
        [ 5.56485757e-17, -1.09395876e-16,  1.00000000e+00]]),
 array([[False, False, False],
        [False, False, False],
        [False, False,  True]]))